SELECT 
    ORD.ORDER_ID, 
    CAT.MANUFACTURER,
    CAT.ITEM_NAME,
    CUST.FIRST_NAME,
    CUST.LAST_NAME,
    CUST.ADDRESS_DISTRICT,
    CUST.ADDRESS_REGION,
    CAT.PRICE_CZK
FROM CUSTOMERS CUST 
INNER JOIN ORDERS ORD
    ON ORD.CUSTOMER_ID = CUST.CUSTOMER_ID
INNER JOIN ITEM_CATALOGUE CAT
    ON CAT.ITEM_ID = ORD.ITEM_ID
WHERE CUST.ADDRESS_REGION = 'Hlavní město Praha'
    AND CAT.PRICE_CZK <= 10000;