CREATE TABLE ORDERS(
ORDER_ID NUMBER(10),
ITEM_ID NUMBER(10),
CUSTOMER_ID NUMBER(10),
CONSTRAINT ORDERS_PRIMARY_KEY PRIMARY KEY (ORDER_ID)
);

CREATE TABLE ITEM_CATALOGUE (
ITEM_ID NUMBER(10),
ITEM_NAME VARCHAR2(50),
MANUFACTURER VARCHAR2(50),
PRICE_CZK NUMBER(20),
CONSTRAINT ITEMS_PRIMARY_KEY PRIMARY KEY (ITEM_ID)
);

CREATE TABLE CUSTOMERS (
CUSTOMER_ID NUMBER(20),
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
ADDRESS_STREET VARCHAR2(50),
ADDRESS_DISTRICT VARCHAR2(50),
ADDRESS_REGION VARCHAR2(50),
CONSTRAINT CUSTOMERS_PRIMARY_KEY PRIMARY KEY (CUSTOMER_ID)
);